# Generated by Django 3.1.14 on 2024-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='pulse',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
