# Generated by Django 3.2.6 on 2023-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_farm_farmname'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='polygon',
            field=models.TextField(blank=True, default=''),
        ),
    ]
