# Generated by Django 3.2.6 on 2023-03-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_farm_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='polygon',
            field=models.TextField(default='', null=True),
        ),
    ]
