# Generated by Django 3.2.6 on 2023-03-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_farm_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='polygon',
            field=models.TextField(blank=True, default=''),
        ),
    ]
