# Generated by Django 4.2.2 on 2023-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_farm_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, default='Sensor Default Unit', max_length=200, null=True),
        ),
    ]
