# Generated by Django 4.2.2 on 2023-12-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_result_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='AirTC_AvgUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='AirTC_MaxUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='AirTC_MinUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='AirTC_TMnUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='AirTC_TMxUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='BP_mmHg_AvgUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='BattV_AvgUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='BattV_MinUnit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='PTemp_C_AvgUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='RHUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='Rain_mm_TotUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='SlrMJ_TotUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='SlrkW_AvgUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='Visibility_m_AvgUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='wind_speed_AVGUnit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
