# Generated by Django 4.2.2 on 2023-12-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_weatherstation_airtc_avgunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='packet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
