# Generated by Django 4.2.2 on 2023-12-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_weatherstation_packet'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetresult',
            name='AirTC_Avg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='AirTC_Max',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='AirTC_Min',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='AirTC_TMn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='AirTC_TMx',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='BP_mmHg_Avg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='BattV_Avg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='BattV_Min',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='PTemp_C_Avg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='RH',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='Rain_mm_Tot',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='SlrMJ_Tot',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='SlrkW_Avg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='Visibility_m_Avg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='packetresult',
            name='wind_speed_AVG',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
