# Generated by Django 4.2.2 on 2023-12-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_packetresult_airtc_avg_packetresult_airtc_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetresult',
            name='direction',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='packetresult',
            name='humidity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='packetresult',
            name='rainfall',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='packetresult',
            name='solar_radiation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='packetresult',
            name='temperature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='packetresult',
            name='timestamp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='packetresult',
            name='visibility',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='packetresult',
            name='wind_speed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
