# Generated by Django 4.2.2 on 2023-12-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_packetresult_airtc_avgunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='valve',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='valve',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
