# Generated by Django 4.2.2 on 2024-01-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_homeuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeUser',
        ),
    ]
