# Generated by Django 4.2.2 on 2024-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_farm_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
